language: java

jdk:
  - openjdk15

sudo: false

env:
  global:
    - CODECOV_TOKEN=359a4666-7e6d-4770-b9df-011f58173a5a

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email:
    recipients:
      - asultangareev@gmail.com
    on_success: never # default: change
    on_failure: always # default: always